# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefix', models.CharField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intent_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intent_Type', models.CharField(choices=[(b'HEAT_PUMP', b'heat_pump'), (b'FAN_BLOWER', b'fan_blower'), (b'OUTDOOR_TEMPERATURE', b'outdoor_temperature'), (b'OUTDOOR_HUMIDITY', b'outdoor_humidity'), (b'NATURAL_GAS', b'natural_gas')], default=None, max_length=60)),
                ('Source_IP', models.CharField(max_length=60)),
                ('Destination_IP', models.CharField(max_length=60)),
                ('Path', models.CharField(max_length=60)),
                ('timestamp', models.DateTimeField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Intent_Path_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cookie', models.CharField(max_length=60)),
                ('priority', models.IntegerField()),
                ('active', models.BooleanField()),
                ('ipv4_src', models.CharField(max_length=60)),
                ('ipv4_dst', models.CharField(max_length=60)),
                ('in_port', models.IntegerField()),
                ('actions', models.CharField(max_length=500)),
                ('Path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Intent_Data')),
            ],
        ),
    ]
