# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent_data',
            name='Intent_Type',
            field=models.CharField(choices=[(b'LATENCY', b'latency'), (b'BANDWIDTH', b'bandwidth'), (b'HOP_COUNT', b'hop_count')], default=None, max_length=60),
        ),
    ]
