# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Fname',
            new_name='Customer_firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Lname',
            new_name='Customer_lastname',
        ),
    ]
