# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Connected_Host',
            field=models.CharField(default=b'20.0.0.1', max_length=60),
        ),
    ]
