# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_connected_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intent_data',
            name='Customer',
        ),
        migrations.AddField(
            model_name='intent_data',
            name='From_Location',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='intent_data',
            name='To_Location',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
