# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180224_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Password',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Prefix',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Username',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_firstname',
            new_name='Prefix',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_lastname',
            new_name='Username',
        ),
        migrations.RenameField(
            model_name='intent_path_data',
            old_name='path_name',
            new_name='Path',
        ),
    ]
