# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180403_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent_data',
            name='Intent_Type',
            field=models.CharField(choices=[(b'LEAST_LATENCY', b'least_latency'), (b'HIGH_BANDWIDTH', b'high_bandwidth'), (b'LEAST_HOP_COUNT', b'least_hop_count')], default=None, max_length=60),
        ),
    ]
